title: tni-unofficial-docs
description: Generated docs/info for the game Tower Networking Inc
baseurl: "/tni-unofficial-docs"
url: "https://avril112113.github.io"
github_username: Avril112113

theme: just-the-docs

plugins:
  - jekyll-include-cache
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607

exclude:
  - ./tools/DeviceCalc/src

favicon_ico: "/favicon.ico"

color_scheme: dark

aux_links:
  "Github":
    - "https://github.com/Avril112113/tni-unofficial-docs"
  "TNI Discord":
    - "https://discord.gg/gMtxdgRu5b"
  "TNI on Steam":
    - "https://store.steampowered.com/app/2939600/Tower_Networking_Inc/"

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true 
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/Avril112113/tni-unofficial-docs"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"
