title: tni-unofficial-docs
description: Generated docs/info for the game Tower Networking Inc
baseurl: "/tni-unofficial-docs"
url: "https://avril112113.github.io"
github_username: Avril112113

source: pages

# remote_theme: just-the-docs/just-the-docs
theme: just-the-docs
plugins:
  - jekyll-include-cache


color_scheme: dark

aux_links:
  "Github":
    - "https://github.com/Avril112113/tni-unofficial-docs"

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true 
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/Avril112113/tni-unofficial-docs"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"
